/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CAddEmployee;
import controller.CLogin;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class VAddEmployee extends javax.swing.JFrame {

    private String empid;
    private String type;
    public VAddEmployee(String empid, String type) {
        this.empid = empid;
        this.type = type;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("Name");
                model.addColumn("Gender");
                model.addColumn("Position");
                model.addColumn("Phone");
                model.addColumn("Email");
        tbl_Employee.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_Gender = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lbl_Home = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_LogOut = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        lbl_Container = new javax.swing.JLabel();
        pnl_Containner = new javax.swing.JPanel();
        btn_DriverManagment = new javax.swing.JButton();
        btn_RoomManagment = new javax.swing.JButton();
        btn_EmployeeManagment = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Age = new javax.swing.JTextField();
        radio_Male = new javax.swing.JRadioButton();
        radio_Female = new javax.swing.JRadioButton();
        txt_Salary = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        pwd_Password = new javax.swing.JPasswordField();
        cmb_Position = new javax.swing.JComboBox<>();
        btn_Save = new javax.swing.JButton();
        btn_Cancle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_Emp_ID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_Search = new javax.swing.JButton();
        btn_Remove = new javax.swing.JButton();
        btn_R_Cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Employee = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        lbl_Home.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.png"))); // NOI18N
        lbl_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HomeMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext459686165626074.png"))); // NOI18N

        lbl_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbl_LogOut.setForeground(new java.awt.Color(255, 204, 0));
        lbl_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/210121 (1).png"))); // NOI18N
        lbl_LogOut.setText("Log Out");
        lbl_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_LogOutMousePressed(evt);
            }
        });

        lbl_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        lbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_UserMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(lbl_LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_User)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_Home)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lbl_Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/output-onlinepngtools (2).png"))); // NOI18N
        lbl_Container.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ContainerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_ContainerMouseReleased(evt);
            }
        });

        pnl_Containner.setBackground(new java.awt.Color(0, 0, 102));

        btn_DriverManagment.setBackground(new java.awt.Color(0, 0, 102));
        btn_DriverManagment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DriverManagment.setForeground(new java.awt.Color(255, 204, 0));
        btn_DriverManagment.setText("Driver Managment");
        btn_DriverManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DriverManagmentActionPerformed(evt);
            }
        });

        btn_RoomManagment.setBackground(new java.awt.Color(0, 0, 102));
        btn_RoomManagment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_RoomManagment.setForeground(new java.awt.Color(255, 204, 0));
        btn_RoomManagment.setText("Room Managment");
        btn_RoomManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RoomManagmentActionPerformed(evt);
            }
        });

        btn_EmployeeManagment.setBackground(new java.awt.Color(0, 0, 102));
        btn_EmployeeManagment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EmployeeManagment.setForeground(new java.awt.Color(255, 204, 0));
        btn_EmployeeManagment.setText("Employee Managment");
        btn_EmployeeManagment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeManagmentActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setText("Hotel Everland");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hotel-40.png"))); // NOI18N

        javax.swing.GroupLayout pnl_ContainnerLayout = new javax.swing.GroupLayout(pnl_Containner);
        pnl_Containner.setLayout(pnl_ContainnerLayout);
        pnl_ContainnerLayout.setHorizontalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ContainnerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel15)))
                        .addGap(51, 51, 51))
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_RoomManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_EmployeeManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DriverManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_ContainnerLayout.setVerticalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(btn_EmployeeManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_RoomManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_DriverManagment, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Employee Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Position");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Salary");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Password");

        txt_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AgeActionPerformed(evt);
            }
        });

        btng_Gender.add(radio_Male);
        radio_Male.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radio_Male.setText("Male");
        radio_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_MaleActionPerformed(evt);
            }
        });

        btng_Gender.add(radio_Female);
        radio_Female.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radio_Female.setText("Female");

        txt_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SalaryActionPerformed(evt);
            }
        });

        txt_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneActionPerformed(evt);
            }
        });

        cmb_Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Admin" }));

        btn_Save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Cancle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cancle.setText("Cancle");
        btn_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(127, 127, 127))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Cancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Name)
                            .addComponent(txt_Phone)
                            .addComponent(txt_Email)
                            .addComponent(pwd_Password)
                            .addComponent(btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(radio_Male)
                                    .addGap(36, 36, 36)
                                    .addComponent(radio_Female))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Salary, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_Position, javax.swing.GroupLayout.Alignment.LEADING, 0, 98, Short.MAX_VALUE)))
                            .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_Male)
                        .addComponent(radio_Female)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pwd_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Employee ID");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Remove Employee");

        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_Remove.setText("Remove");
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        btn_R_Cancel.setText("Cancel");
        btn_R_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_R_CancelActionPerformed(evt);
            }
        });

        tbl_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Employee);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_R_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(99, 99, 99)
                                        .addComponent(txt_Emp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(84, 84, 84)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(jLabel12))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_Emp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_R_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("REMOVE", jPanel2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Employee Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Containner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Container)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel16)))
                .addContainerGap(464, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_Container)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_Containner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AgeActionPerformed

    private void txt_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SalaryActionPerformed

    private void txt_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneActionPerformed

    private void radio_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_MaleActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        try{
           String id, name, age, gender, position, salary, phone, email, password;
           char [] passwd;
           
           id = txt_ID.getText();
           name = txt_Name.getText();
           age = txt_Age.getText();
           
           if(radio_Male.isSelected()){
               gender = "Male";
           }
           else{
               gender = "Female";
           }
           
           position = cmb_Position.getSelectedItem().toString();
           salary = txt_Salary.getText();
           phone = txt_Phone.getText();
           email = txt_Email.getText();
           passwd = pwd_Password.getPassword();
           password = new String(passwd);
           
           CAddEmployee cae = new CAddEmployee();
           cae.AddEmployee(id, name, age, gender, position, salary, phone, email, password);
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancleActionPerformed
        // TODO add your handling code here:
        txt_ID.setText("");
        txt_Name.setText("");
        txt_Age.setText("");
        cmb_Position.setSelectedIndex(0);
        txt_Salary.setText("");
        txt_Phone.setText("");
        txt_Email.setText("");
        pwd_Password.setText("");
    }//GEN-LAST:event_btn_CancleActionPerformed

    private void lbl_ContainerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ContainerMousePressed
        // TODO add your handling code here:
        pnl_Containner.setVisible(false);
    }//GEN-LAST:event_lbl_ContainerMousePressed

    private void lbl_ContainerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ContainerMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ContainerMouseReleased

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        try{
            String id = txt_Emp_ID.getText();
        
            CAddEmployee cae = new CAddEmployee();
            ResultSet rst = cae.SearchEmployee(id);

            DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("Name");
                model.addColumn("Gender");
                model.addColumn("Position");
                model.addColumn("Phone");
                model.addColumn("Email");

                boolean hasData = false;
                while (rst.next()) {
                    hasData = true;
                    Vector<String> row = new Vector<>();
                    row.add(rst.getString("empid"));
                    row.add(rst.getString("name"));
                    row.add(rst.getString("gender"));
                    row.add(rst.getString("position"));
                    row.add(rst.getString("phone"));
                    row.add(rst.getString("email"));
                    model.addRow(row);
                }
             
            if(!hasData){
                JOptionPane.showMessageDialog(this, "Incorrect Employee ID!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                tbl_Employee.setModel(model);
            }
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed
        // TODO add your handling code here:
        try{
            String id = txt_Emp_ID.getText();
            
            CAddEmployee cae = new CAddEmployee();
            cae.RemoveEmployee(id);
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void btn_DriverManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DriverManagmentActionPerformed
        // TODO add your handling code here:
        VDriversManagement vae = new VDriversManagement(empid, type);
        vae.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DriverManagmentActionPerformed

    private void btn_RoomManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RoomManagmentActionPerformed
        // TODO add your handling code here:
        VAddRoom vdm = new VAddRoom(empid, type);
        vdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RoomManagmentActionPerformed

    private void btn_EmployeeManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeManagmentActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_btn_EmployeeManagmentActionPerformed

    private void lbl_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HomeMousePressed
        // TODO add your handling code here:
        VAdminDashboard vad = new VAdminDashboard(empid, type);
        vad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_HomeMousePressed

    private void lbl_LogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMousePressed
        // TODO add your handling code here:
        CLogin login = new CLogin();
        login.SaveLogOut(empid, type);
        this.dispose();
        VAdminDashboard vadmin = new VAdminDashboard(empid, type);
        vadmin.dispose();
        VLogin vlogin = new VLogin();
        vlogin.setVisible(true);
    }//GEN-LAST:event_lbl_LogOutMousePressed

    private void btn_R_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_R_CancelActionPerformed
        // TODO add your handling code here:
        txt_Emp_ID.setText("");
        DefaultTableModel model = (DefaultTableModel) tbl_Employee.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btn_R_CancelActionPerformed

    private void lbl_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UserMousePressed
        // TODO add your handling code here:
        VUser user = new VUser(empid);
        user.setVisible(true);
    }//GEN-LAST:event_lbl_UserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAddEmployee("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancle;
    private javax.swing.JButton btn_DriverManagment;
    private javax.swing.JButton btn_EmployeeManagment;
    private javax.swing.JButton btn_R_Cancel;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_RoomManagment;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Search;
    private javax.swing.ButtonGroup btng_Gender;
    private javax.swing.JComboBox<String> cmb_Position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Container;
    private javax.swing.JLabel lbl_Home;
    private javax.swing.JLabel lbl_LogOut;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPanel pnl_Containner;
    private javax.swing.JPasswordField pwd_Password;
    private javax.swing.JRadioButton radio_Female;
    private javax.swing.JRadioButton radio_Male;
    private javax.swing.JTable tbl_Employee;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Emp_ID;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_Salary;
    // End of variables declaration//GEN-END:variables
}
