/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CCheckIn;
import controller.CLogin;
import controller.CSelectRoom;
import javax.swing.JFrame;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;


public class VCheckIn extends javax.swing.JFrame {
    
    private String empid;
    private String type;
    public VCheckIn(String empid, String type) {
        this.empid = empid;
        this.type = type;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        date_Checkin.setMinSelectableDate(new Date());
        date_Checkout.setMinSelectableDate(new Date());
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Name");
            model.addColumn("Room Type");
            model.addColumn("Adults");
            model.addColumn("Children");
            model.addColumn("Check-in");
            model.addColumn("Check-out");
            
        table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbl_Home = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_LogOut = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        lbl_Container = new javax.swing.JLabel();
        pnl_Containner = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Riservation = new javax.swing.JButton();
        btn_RoomAvailability = new javax.swing.JButton();
        btn_Register = new javax.swing.JButton();
        btn_CheckIn = new javax.swing.JButton();
        btn_ChekOut = new javax.swing.JButton();
        btn_Driver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_Checkin = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_ResID = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        spn_NoOfRoom = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmb_ID = new javax.swing.JComboBox<>();
        txt_Number = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        date_Checkin = new com.toedter.calendar.JDateChooser();
        date_Checkout = new com.toedter.calendar.JDateChooser();
        spn_Adult = new javax.swing.JSpinner();
        spn_Children = new javax.swing.JSpinner();
        cmb_Roomtype = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_SelectRoomNumbers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        lbl_Home.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.png"))); // NOI18N
        lbl_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HomeMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext459686165626074.png"))); // NOI18N

        lbl_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbl_LogOut.setForeground(new java.awt.Color(255, 204, 0));
        lbl_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/210121 (1).png"))); // NOI18N
        lbl_LogOut.setText("Log Out");
        lbl_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_LogOutMousePressed(evt);
            }
        });

        lbl_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        lbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_UserMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(lbl_LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_User)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_Home)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lbl_Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/output-onlinepngtools (2).png"))); // NOI18N
        lbl_Container.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ContainerMousePressed(evt);
            }
        });

        pnl_Containner.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hotel-40.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Hotel Everland");

        btn_Riservation.setBackground(new java.awt.Color(0, 0, 102));
        btn_Riservation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Riservation.setForeground(new java.awt.Color(255, 204, 0));
        btn_Riservation.setText("Riservation");
        btn_Riservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RiservationActionPerformed(evt);
            }
        });

        btn_RoomAvailability.setBackground(new java.awt.Color(0, 0, 102));
        btn_RoomAvailability.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_RoomAvailability.setForeground(new java.awt.Color(255, 204, 0));
        btn_RoomAvailability.setText("Room Availability");
        btn_RoomAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RoomAvailabilityActionPerformed(evt);
            }
        });

        btn_Register.setBackground(new java.awt.Color(0, 0, 102));
        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Register.setForeground(new java.awt.Color(255, 204, 0));
        btn_Register.setText("Register");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        btn_CheckIn.setBackground(new java.awt.Color(0, 0, 102));
        btn_CheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CheckIn.setForeground(new java.awt.Color(255, 204, 0));
        btn_CheckIn.setText("Check-In");
        btn_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckInActionPerformed(evt);
            }
        });

        btn_ChekOut.setBackground(new java.awt.Color(0, 0, 102));
        btn_ChekOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ChekOut.setForeground(new java.awt.Color(255, 204, 0));
        btn_ChekOut.setText("Check-Out");
        btn_ChekOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChekOutActionPerformed(evt);
            }
        });

        btn_Driver.setBackground(new java.awt.Color(0, 0, 102));
        btn_Driver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Driver.setForeground(new java.awt.Color(255, 204, 0));
        btn_Driver.setText("Driver");
        btn_Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ContainnerLayout = new javax.swing.GroupLayout(pnl_Containner);
        pnl_Containner.setLayout(pnl_ContainnerLayout);
        pnl_ContainnerLayout.setHorizontalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Riservation, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ChekOut, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ContainnerLayout.setVerticalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(btn_Riservation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ChekOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Check-In");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Reservation ID");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Name");

        btn_Checkin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Checkin.setText("Check-In");
        btn_Checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckinActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Check-in");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Room Type");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Check-out");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Adult");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Children");

        txt_ResID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ResIDActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("No of Rooms");

        spn_NoOfRoom.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Number");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("ID");

        cmb_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIC", "Passport", "Driving License" }));
        cmb_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_IDActionPerformed(evt);
            }
        });

        txt_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NumberActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Rooms Numbers");

        btn_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        date_Checkin.setBackground(new java.awt.Color(255, 255, 255));
        date_Checkin.setEnabled(false);

        spn_Adult.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spn_Children.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cmb_Roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Suite" }));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jScrollPane3.setViewportView(jScrollPane2);

        btn_SelectRoomNumbers.setText("Select");
        btn_SelectRoomNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelectRoomNumbersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spn_Adult, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel33))
                        .addGap(668, 668, 668))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btn_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(90, 90, 90)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spn_Children, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_Roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(date_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spn_NoOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_SelectRoomNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(94, 94, 94)
                                        .addComponent(txt_ResID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_ResID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cmb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cmb_Roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(spn_NoOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(btn_SelectRoomNumbers))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(date_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(date_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(spn_Adult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(spn_Children, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_Container))
                    .addComponent(pnl_Containner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Container)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_Containner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HomeMousePressed
        // TODO add your handling code here:
        VStaffDashboard vstaff = new VStaffDashboard(empid, type);
        vstaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_HomeMousePressed

    private void lbl_LogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMousePressed
        // TODO add your handling code here:
        CLogin login = new CLogin();
        login.SaveLogOut(empid, type);
        this.dispose();
        VStaffDashboard vstaff = new VStaffDashboard(empid, type);
        vstaff.dispose();
        VLogin vlogin = new VLogin();
        vlogin.setVisible(true);
    }//GEN-LAST:event_lbl_LogOutMousePressed

    private void lbl_ContainerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ContainerMousePressed
        // TODO add your handling code here:
        pnl_Containner.setVisible(false);
    }//GEN-LAST:event_lbl_ContainerMousePressed

    private void btn_CheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckinActionPerformed
        // TODO add your handling code here:
        try{
            String resid,id,number,name,roomType;
            int noOfRoom,adult,children;
            Date checkin,checkout;
            
            resid = txt_ResID.getText();
            id = cmb_ID.getSelectedItem().toString();
            number = txt_Number.getText();
            name = txt_Name.getText();
            checkin = date_Checkin.getDate();
            checkout = date_Checkout.getDate();
            roomType = cmb_Roomtype.getSelectedItem().toString();
            noOfRoom = (int) spn_NoOfRoom.getValue();
            adult = (int) spn_Adult.getValue();
            children = (int) spn_Children.getValue();
            
            
            CCheckIn cci = new CCheckIn();
            cci.SaveCheckIn(resid, id, number, name, adult, children, roomType, noOfRoom, checkin, checkout);
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_CheckinActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        // Clear the input fields
        txt_Number.setText("");
        txt_ResID.setText("");
        txt_Name.setText("");
        cmb_Roomtype.setSelectedIndex(0); // Assuming the first item is a default value
        spn_Adult.setValue(0);
        spn_Children.setValue(0);
        date_Checkin.setDate(null);
        date_Checkout.setDate(null);

        // Clear the table model
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void cmb_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_IDActionPerformed

    private void txt_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NumberActionPerformed

    private void txt_ResIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ResIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ResIDActionPerformed

    private void btn_RiservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RiservationActionPerformed
        // TODO add your handling code here:
        VReservation vr = new VReservation(empid, type);
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RiservationActionPerformed

    private void btn_RoomAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RoomAvailabilityActionPerformed
        // TODO add your handling code here:
        VRoomAvailability vra = new VRoomAvailability(empid, type);
        vra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RoomAvailabilityActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        VGuestAdd vga = new VGuestAdd(empid, type);
        vga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void btn_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckInActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_btn_CheckInActionPerformed

    private void btn_ChekOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChekOutActionPerformed
        // TODO add your handling code here:
        VCheckOut vco = new VCheckOut(empid, type);
        vco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ChekOutActionPerformed

    private void btn_DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DriverActionPerformed
        // TODO add your handling code here:
        VDriverBooking vdb = new VDriverBooking(empid, type);
        vdb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DriverActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        try{
            String resID;
        
            resID = txt_ResID.getText();

            CCheckIn ccis = new CCheckIn();
            ResultSet rst = ccis.SearchCheckIn(resID);
            
            if(!rst.next()){
                JOptionPane.showMessageDialog(this, "No reservation found with the provided ID.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Name");
            model.addColumn("Room Type");
            model.addColumn("Adults");
            model.addColumn("Children");
            model.addColumn("Check-in");
            model.addColumn("Check-out");

            do{
                Vector<String> row = new Vector<>();
                row.add(rst.getString("name"));
                row.add(rst.getString("roomtype"));
                row.add(String.valueOf(rst.getInt("adult")));
                row.add(String.valueOf(rst.getInt("children")));
                row.add(rst.getDate("checkin").toString());
                row.add(rst.getDate("checkout").toString());
                model.addRow(row);
                
                txt_Name.setText(rst.getString("name"));
                cmb_Roomtype.setSelectedItem(rst.getString("roomtype"));
                spn_Adult.setValue(rst.getInt("adult"));
                spn_Children.setValue(rst.getInt("children"));
                date_Checkin.setDate(new Date());
            }while(rst.next());
            
            table.setModel(model);
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_SelectRoomNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelectRoomNumbersActionPerformed
        // TODO add your handling code here:
        try{
            String resID,id,number,roomType;
            
            resID = txt_ResID.getText();
            id = cmb_ID.getSelectedItem().toString();
            number = txt_Number.getText();
            roomType = cmb_Roomtype.getSelectedItem().toString();
            
            CSelectRoom csr = new CSelectRoom();
            ResultSet rst = csr.getAvailableRoomNumbers(roomType);
            if(rst.next()){
                VSelectRoom room = new VSelectRoom(resID,id,number,roomType);
                room.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "No Available Rooms!", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_SelectRoomNumbersActionPerformed

    private void lbl_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UserMousePressed
        // TODO add your handling code here:
        VUser user = new VUser(empid);
        user.setVisible(true);
    }//GEN-LAST:event_lbl_UserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCheckIn("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_CheckIn;
    private javax.swing.JButton btn_Checkin;
    private javax.swing.JButton btn_ChekOut;
    private javax.swing.JButton btn_Driver;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Riservation;
    private javax.swing.JButton btn_RoomAvailability;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_SelectRoomNumbers;
    private javax.swing.JComboBox<String> cmb_ID;
    private javax.swing.JComboBox<String> cmb_Roomtype;
    private com.toedter.calendar.JDateChooser date_Checkin;
    private com.toedter.calendar.JDateChooser date_Checkout;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Container;
    private javax.swing.JLabel lbl_Home;
    private javax.swing.JLabel lbl_LogOut;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPanel pnl_Containner;
    private javax.swing.JSpinner spn_Adult;
    private javax.swing.JSpinner spn_Children;
    private javax.swing.JSpinner spn_NoOfRoom;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Number;
    private javax.swing.JTextField txt_ResID;
    // End of variables declaration//GEN-END:variables
}
