/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CLogin;
import controller.CRoomAvailability;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author acer
 */
public class VRoomAvailability extends javax.swing.JFrame {

    private String empid;
    private String type;
    public VRoomAvailability(String empid, String type) {
        this.empid = empid;
        this.type = type;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Room No");
            model.addColumn("Room Type");
            model.addColumn("Status");
        tbl_RoomAvailability.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Containner = new javax.swing.JPanel();
        btn_Riservation = new javax.swing.JButton();
        btn_RoomAvailability = new javax.swing.JButton();
        btn_Register = new javax.swing.JButton();
        btn_CheckIn = new javax.swing.JButton();
        btn_ChekOut = new javax.swing.JButton();
        btn_Driver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Container = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_Home = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_LogOut = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_RoomType = new javax.swing.JComboBox<>();
        btn_Check = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_RoomAvailability = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Containner.setBackground(new java.awt.Color(0, 0, 102));

        btn_Riservation.setBackground(new java.awt.Color(0, 0, 102));
        btn_Riservation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Riservation.setForeground(new java.awt.Color(255, 204, 0));
        btn_Riservation.setText("Riservation");
        btn_Riservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RiservationActionPerformed(evt);
            }
        });

        btn_RoomAvailability.setBackground(new java.awt.Color(0, 0, 102));
        btn_RoomAvailability.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_RoomAvailability.setForeground(new java.awt.Color(255, 204, 0));
        btn_RoomAvailability.setText("Room Availability");
        btn_RoomAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RoomAvailabilityActionPerformed(evt);
            }
        });

        btn_Register.setBackground(new java.awt.Color(0, 0, 102));
        btn_Register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Register.setForeground(new java.awt.Color(255, 204, 0));
        btn_Register.setText("Register");
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });

        btn_CheckIn.setBackground(new java.awt.Color(0, 0, 102));
        btn_CheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CheckIn.setForeground(new java.awt.Color(255, 204, 0));
        btn_CheckIn.setText("Check-In");
        btn_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckInActionPerformed(evt);
            }
        });

        btn_ChekOut.setBackground(new java.awt.Color(0, 0, 102));
        btn_ChekOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ChekOut.setForeground(new java.awt.Color(255, 204, 0));
        btn_ChekOut.setText("Check-Out");
        btn_ChekOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChekOutActionPerformed(evt);
            }
        });

        btn_Driver.setBackground(new java.awt.Color(0, 0, 102));
        btn_Driver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Driver.setForeground(new java.awt.Color(255, 204, 0));
        btn_Driver.setText("Driver");
        btn_Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DriverActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hotel-40.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Hotel Everland");

        javax.swing.GroupLayout pnl_ContainnerLayout = new javax.swing.GroupLayout(pnl_Containner);
        pnl_Containner.setLayout(pnl_ContainnerLayout);
        pnl_ContainnerLayout.setHorizontalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Riservation, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ChekOut, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ContainnerLayout.setVerticalGroup(
            pnl_ContainnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContainnerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(btn_Riservation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ChekOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        lbl_Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/output-onlinepngtools (2).png"))); // NOI18N
        lbl_Container.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ContainerMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        lbl_Home.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.png"))); // NOI18N
        lbl_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HomeMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext459686165626074.png"))); // NOI18N

        lbl_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbl_LogOut.setForeground(new java.awt.Color(255, 204, 0));
        lbl_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/210121 (1).png"))); // NOI18N
        lbl_LogOut.setText("Log Out");
        lbl_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_LogOutMousePressed(evt);
            }
        });

        lbl_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        lbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_UserMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(lbl_LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_User)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_Home)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Room Availability");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Room Type");

        cmb_RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Suite" }));

        btn_Check.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Check.setText("Check");
        btn_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckActionPerformed(evt);
            }
        });

        tbl_RoomAvailability.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_RoomAvailability);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_Container))
                            .addComponent(pnl_Containner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(198, 198, 198)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Container)
                        .addGap(8, 8, 8)
                        .addComponent(pnl_Containner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RiservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RiservationActionPerformed
        // TODO add your handling code here:
        VReservation vr = new VReservation(empid, type);
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RiservationActionPerformed

    private void btn_RoomAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RoomAvailabilityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_RoomAvailabilityActionPerformed

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
        // TODO add your handling code here:
        VGuestAdd vga = new VGuestAdd(empid, type);
        vga.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void btn_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckInActionPerformed
        // TODO add your handling code here:
        VCheckIn vci = new VCheckIn(empid, type);
        vci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CheckInActionPerformed

    private void btn_ChekOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChekOutActionPerformed
        // TODO add your handling code here:
        VCheckOut vco = new VCheckOut(empid, type);
        vco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ChekOutActionPerformed

    private void btn_DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DriverActionPerformed
        // TODO add your handling code here:
        VDriverBooking vra = new VDriverBooking(empid, type);
        vra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DriverActionPerformed

    private void lbl_ContainerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ContainerMousePressed
        // TODO add your handling code here:
        pnl_Containner.setVisible(false);
    }//GEN-LAST:event_lbl_ContainerMousePressed

    private void lbl_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HomeMousePressed
        // TODO add your handling code here:
        VStaffDashboard vstaff = new VStaffDashboard(empid, type);
        vstaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_HomeMousePressed

    private void lbl_LogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOutMousePressed
        // TODO add your handling code here:
        CLogin login = new CLogin();
        login.SaveLogOut(empid, type);
        this.dispose();
        VStaffDashboard vstaff = new VStaffDashboard(empid, type);
        vstaff.dispose();
        VLogin vlogin = new VLogin();
        vlogin.setVisible(true);
    }//GEN-LAST:event_lbl_LogOutMousePressed

    private void btn_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckActionPerformed
        // TODO add your handling code here:
        try{
            String roomType = cmb_RoomType.getSelectedItem().toString();
        
            CRoomAvailability cra = new CRoomAvailability();
            ResultSet rst = cra.CheckRoomAvailability(roomType);

            DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Room No");
                model.addColumn("Room Type");
                model.addColumn("Status");

                boolean hasData = false;
                while (rst.next()) {
                    hasData = true;
                    Vector<String> row = new Vector<>();
                    row.add(rst.getString("roomNo"));
                    row.add(rst.getString("roomType"));
                    row.add(rst.getString("status"));
                    model.addRow(row);
                }
             
            if(!hasData){
                JOptionPane.showMessageDialog(this, "No available rooms.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                tbl_RoomAvailability.setModel(model);
            }
        }
        catch(Exception e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_CheckActionPerformed

    private void lbl_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UserMousePressed
        // TODO add your handling code here:
        VUser user = new VUser(empid);
        user.setVisible(true);
    }//GEN-LAST:event_lbl_UserMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRoomAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRoomAvailability("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Check;
    private javax.swing.JButton btn_CheckIn;
    private javax.swing.JButton btn_ChekOut;
    private javax.swing.JButton btn_Driver;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_Riservation;
    private javax.swing.JButton btn_RoomAvailability;
    private javax.swing.JComboBox<String> cmb_RoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Container;
    private javax.swing.JLabel lbl_Home;
    private javax.swing.JLabel lbl_LogOut;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPanel pnl_Containner;
    private javax.swing.JTable tbl_RoomAvailability;
    // End of variables declaration//GEN-END:variables
}
