/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CLogin;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class VStaffDashboard extends javax.swing.JFrame {

    private String empid;
    private String type;
    public VStaffDashboard(String empid, String type) {
        this.empid = empid;
        this.type = type;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        lbl_Home2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_LogOut2 = new javax.swing.JLabel();
        lbl_User2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Add_Customers = new javax.swing.JButton();
        btn_RoomAvailability = new javax.swing.JButton();
        btn_CheckIn = new javax.swing.JButton();
        btn_Driver = new javax.swing.JButton();
        btn_CheckOut = new javax.swing.JButton();
        btn_Reservation = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        lbl_Home2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Home2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hotel-40.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext459686165626074.png"))); // NOI18N

        lbl_LogOut2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbl_LogOut2.setForeground(new java.awt.Color(255, 204, 0));
        lbl_LogOut2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/210121 (1).png"))); // NOI18N
        lbl_LogOut2.setText("Log Out");
        lbl_LogOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_LogOut2MousePressed(evt);
            }
        });

        lbl_User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        lbl_User2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_User2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Home2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342)
                .addComponent(lbl_LogOut2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_User2)
                .addGap(11, 11, 11))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_User2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_LogOut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbl_Home2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext459915817729506.png"))); // NOI18N

        btn_Add_Customers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Add_Customers.setForeground(new java.awt.Color(0, 0, 102));
        btn_Add_Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-registration-64.png"))); // NOI18N
        btn_Add_Customers.setText("Register Customer");
        btn_Add_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_CustomersActionPerformed(evt);
            }
        });

        btn_RoomAvailability.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_RoomAvailability.setForeground(new java.awt.Color(0, 0, 102));
        btn_RoomAvailability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-room-64.png"))); // NOI18N
        btn_RoomAvailability.setText("Room Availability");
        btn_RoomAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RoomAvailabilityActionPerformed(evt);
            }
        });

        btn_CheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CheckIn.setForeground(new java.awt.Color(0, 0, 102));
        btn_CheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-28-checkin-64.png"))); // NOI18N
        btn_CheckIn.setText("     Check-In");
        btn_CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckInActionPerformed(evt);
            }
        });

        btn_Driver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Driver.setForeground(new java.awt.Color(0, 0, 102));
        btn_Driver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-driver-64.png"))); // NOI18N
        btn_Driver.setText("        Driver");
        btn_Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DriverActionPerformed(evt);
            }
        });

        btn_CheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CheckOut.setForeground(new java.awt.Color(0, 0, 102));
        btn_CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-check-out-64.png"))); // NOI18N
        btn_CheckOut.setText("     Check-Out");
        btn_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckOutActionPerformed(evt);
            }
        });

        btn_Reservation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Reservation.setForeground(new java.awt.Color(0, 0, 102));
        btn_Reservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-reservation-64.png"))); // NOI18N
        btn_Reservation.setText("Reservation");
        btn_Reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Add_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RoomAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_CustomersActionPerformed
        // TODO add your handling code here:
        VGuestAdd vga = new VGuestAdd(empid, type);
        vga.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Add_CustomersActionPerformed

    private void btn_RoomAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RoomAvailabilityActionPerformed
        // TODO add your handling code here:
        VRoomAvailability vra = new VRoomAvailability(empid, type);
        vra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_RoomAvailabilityActionPerformed

    private void btn_CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckInActionPerformed
        // TODO add your handling code here:
        VCheckIn vci = new VCheckIn(empid, type);
        vci.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CheckInActionPerformed

    private void btn_DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DriverActionPerformed
        // TODO add your handling code here:
        VDriverBooking vdb = new VDriverBooking(empid, type);
        vdb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_DriverActionPerformed

    private void btn_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckOutActionPerformed
        // TODO add your handling code here:
        VCheckOut vco = new VCheckOut(empid, type);
        vco.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CheckOutActionPerformed

    private void btn_ReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReservationActionPerformed
        // TODO add your handling code here:
        VReservation vr = new VReservation(empid, type);
        vr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ReservationActionPerformed

    private void lbl_LogOut2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogOut2MousePressed
        // TODO add your handling code here:
        CLogin login = new CLogin();
        login.SaveLogOut(empid, type);
        this.dispose();
        VLogin vlogin = new VLogin();
        vlogin.setVisible(true);
    }//GEN-LAST:event_lbl_LogOut2MousePressed

    private void lbl_User2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_User2MousePressed
        // TODO add your handling code here:
        VUser user = new VUser(empid);
        user.setVisible(true);
    }//GEN-LAST:event_lbl_User2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VStaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VStaffDashboard("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add_Customers;
    private javax.swing.JButton btn_CheckIn;
    private javax.swing.JButton btn_CheckOut;
    private javax.swing.JButton btn_Driver;
    private javax.swing.JButton btn_Reservation;
    private javax.swing.JButton btn_RoomAvailability;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_Home2;
    private javax.swing.JLabel lbl_LogOut2;
    private javax.swing.JLabel lbl_User2;
    // End of variables declaration//GEN-END:variables
}
